on: [push]
jobs:
  my-job:
    # Importing a reusable workflow from another repository and branch
    uses: sreekanth014/reusable-2407/.github/workflows/build-test-deploy.yml@master
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '20.x'
